version: '3.8'

services:
  stock-market:
    build: ./stock_market
    environment:
      DATABASE_URL: postgres://postgres:postgres@stock-market-db:5432/postgres
    volumes:
      - ./stock_market:/app
    depends_on:
      - stock-market-db
    ports:
      - '8000:8000'
    tty: true
    command: uvicorn code.app:app --host 0.0.0.0 --reload

  stock-market-worker:
    build: ./stock_market
    environment:
      FINNHUB_API_KEY: cb36h0aad3i3uh8votcg
      DATABASE_URL: postgres://postgres:postgres@stock-market-db:5432/postgres
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./stock_market:/app
    depends_on:
      - stock-market-db
      - rabbitmq
    tty: true
    command: python -m code.worker

  stock-market-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  subscriptions:
    build: ./subscriptions
    environment:
      DATABASE_URL: postgres://postgres:postgres@subscriptions-db:5432/postgres
    volumes:
      - ./subscriptions:/app
    depends_on:
      - subscriptions-db
    ports:
      - '9000:8000'
    tty: true
    command: uvicorn code.app:app --host 0.0.0.0 --reload

  subscriptions-consumer:
    build: ./subscriptions
    environment:
      DATABASE_URL: postgres://postgres:postgres@subscriptions-db:5432/postgres
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./subscriptions:/app
    depends_on:
      - subscriptions-db
      - rabbitmq
    tty: true
    command: python -m code.consumer

  subscriptions-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'

  notifications-consumer:
    build: ./notifications
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 465
      EMAIL_USERNAME: quqanai.quqanai@gmail.com
      EMAIL_PASSWORD: hvzwicxeepalfzge
    volumes:
      - ./notifications:/app
    depends_on:
      - rabbitmq
    tty: true
    command: python -m code.consumer

  rabbitmq:
    image: rabbitmq:alpine
